{% set name = "basemap_data_hires" %}
{% set version = "1.3.2" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/basemap_data_hires-{{ version }}.zip
  sha256: 0982eb95b2066ccbe10b6580bcd9c597e3a4e25016bf25afb65e1a96f6e3e97d

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python <4.0
  run:
    - python <4.0

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: https://matplotlib.org/basemap
  license: LGPL-3.0-or-later 
  license_file: COPYING.LESSER
  summary: High-resolution data assets for matplotlib basemap

extra:
  recipe-maintainers:
    - ocefpaf
    - molinav
    - ReimarBauer
